name: CI
on:
  pull_request:
  push:
    branches: ['**']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v3.5.2

      - name: Set up Gradle JDK
        uses: actions/setup-java@v3.10.0
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2.4.0
        # FIXME: either parse version from properties or implement in action.
        with:
          gradle-version: 7.5.1

      - name: Build with Gradle
        run: gradle build

      - name: Upload artifacts
        uses: actions/upload-artifact@v3.1.2
        with:
          name: libs
          path: |
            */build/libs/*.jar
            !buildSrc

  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v3.5.2

      - name: Set up Gradle JDK
        uses: actions/setup-java@v3.10.0
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2.4.0
        # FIXME: either parse version from properties or implement in action.
        with:
          gradle-version: 7.5.1

      - name: Reformat with Gradle
        run: gradle spotlessApply

      - name: Push changes to origin
        run: |
          git config user.name actions-user
          git config user.email actions@github.com
          git commit -a -m "Format source code" || exit 0
          git push
